### ISSUE TITLE
No tax calculated when county has two words

### ISSUE THREAD

**Issue by hannahswain** [taxjar/taxjar-woocommerce-plugin#113]
Using a UK address, the county field is optional. When filled in with just one word (i.e. Sussex), tax is calculated correctly:

![County - one word](https://cld.wthms.co/JeY97i+)
Full size: https://cld.wthms.co/JeY97i

If a second word is added (i.e. West Sussex), the tax is 0:

![County - two words](https://cld.wthms.co/HItOdA+)
Full size: https://cld.wthms.co/HItOdA

This continues with other examples - setting `county` to "test" returns the correct tax rate, while "test test" returns a zero rate. 

Confirmed on both a customer live site and a test site using WooCommerce Services (TaxJar). 

2126459-zen

**Comment by RiaanKnoetze** [comment]
@hannahswain - This sounds remarkably similar to https://github.com/Automattic/woocommerce-services/issues/1600

**Comment by dallendalton** [comment]
@hannahswain I've been digging into this issue and @RiaanKnoetze is correct that it is the same issue that was mentioned in the WooCommerce Services plugin. It all stems from how WooCommerce handles and stores the state value (its labeled county for UK addresses but is the same field). We are currently evaluating a temporary fix to our plugin that will resolve the issue until WooCommerce changes the handling of that field. This fix will be included in our next release. Thanks!

**Comment by RiaanKnoetze** [comment]
@dallendalton - Just to check: have you opened a report on the WC core repo as well in order for the field handling to be changed to something that'll meet your needs?

**Comment by mikelanemods** [comment]
> @hannahswain - This sounds remarkably similar to [Automattic/woocommerce-services#1600](https://github.com/Automattic/woocommerce-services/issues/1600)

The issue is similar Riaan yes (I reported it), but the step-by-step referenced in /issues/1600/ to replicate the issue isn't quite right. The issue doesn't arise simply because a "county actually exists". The issue arises when **spaces are entered** in the county names. As soon as you add any spaces to the county names the tax will clear to zero. If you guys could work on a fix **asap** I would greatly appreciate it as this issue has cost me thousands in lost tax which I can't find a fix for. It's existed since I launched my site in February. Thank you! Mike

**Comment by mikelanemods** [comment]
Any update on this? I noticed a major update to Jetpack today but still no fix for this major bug?!

**Comment by mikelanemods** [comment]
> @hannahswain I've been digging into this issue and @RiaanKnoetze is correct that it is the same issue that was mentioned in the WooCommerce Services plugin. It all stems from how WooCommerce handles and stores the state value (its labeled county for UK addresses but is the same field). We are currently evaluating a temporary fix to our plugin that will resolve the issue until WooCommerce changes the handling of that field. **_This fix will be included in our next release. Thanks!_**

It wasn't included in your next release. Can you update us on when it will be released asap please? This bug is costing a lot of us a lot of money in lost taxes.

**Comment by dallendalton** [comment]
@mikelanemods - The TaxJar plugin is built and maintained by TaxJar and is separate from Automattic (which owns and maintains WordPress, WooCommerce, JetPack, etc). The issue has been reported to Automattic and hopefully they will resolve it in the core soon. 

Regardless though, we are working on a separate workaround for the TaxJar plugin, which will be released in about two weeks. This release will fix the issue for any tax rates that are calculated by the TaxJar plugin.

**Comment by mikelanemods** [comment]
> @mikelanemods - The TaxJar plugin is built and maintained by TaxJar and is separate from Automattic (which owns and maintains WordPress, WooCommerce, JetPack, etc). The issue has been reported to Automattic and hopefully they will resolve it in the core soon.
> 
> Regardless though, we are working on a separate workaround for the TaxJar plugin, which will be released in about two weeks. This release will fix the issue for any tax rates that are calculated by the TaxJar plugin.

Thats excellent news dallendalton, thank you so much for the update. It's been an ongoing headache since I launched my website back in February, and i'm sure existed long before then for other users too so it's good to hear there's light at the end of the tunnel. Can you let us know here as soon as it is released so we can make the updates. Cheers, Mike

**Comment by mikelanemods** [comment]
Hi dallendalton. Any news? Are we set for a patch this week?

**Comment by dallendalton** [comment]
@mikelanemods - So this is going to be released along with our support for WooCommerce 3.7. It's scheduled to release on Monday!

**Comment by mikelanemods** [comment]
Awesome! Thats great news! Thanks for the update dallendalton

**Comment by dallendalton** [comment]
@mikelanemods This bug has been fixed in version 2.3.1 which was released today. Thanks!

**Comment by mikelanemods** [comment]
Thanks but 2.3.1? My JetPack is on Version 7.6 and I don't see any updates available.

**Comment by mikelanemods** [comment]
Or do you mean 2.3.1 of TaxJar? If so will this ripple through to the Jetpack/WooCommerce plugins as currently there are no updates that I can see and the issue is still present.

**Comment by dallendalton** [comment]
Yep Taxjar version 2.3.1. This update is already available at WordPress.com: https://wordpress.org/plugins/taxjar-simplified-taxes-for-woocommerce/

Your site should detect that an update is available next time it checks for updates. JetPack should also detect that the update is available at that time. To force your site to check for updates you can go to dashboard and then updates. Then click the check again button.

**Comment by mikelanemods** [comment]
Hi dallendalton. So I don't have the taxjar plugin installed, I rely on Jetpack to calculate my taxes. Despite clicking 'check again' there are no updates to Jetpack so i'm left still suffering with this issue unfortunately.

**Comment by dallendalton** [comment]
@mikelanemods Sorry I didn't realize this was the case. This thread is in the TaxJar plugin repository and the fix discussed is for the TaxJar plugin. TaxJar is maintained independently and separately from WooCommerce. The bug in WooCommerce that makes this fix necessary as been reported to them, but if you are not using the TaxJar plugin you will have to wait until they fix the issue in their code. Thanks!
